---
- name: remove syslog-ng if present
  apt: pkg={{ item }}
       update_cache=yes
       state=absent

  with_items:
  - syslog-ng


- name: install rsyslog
  apt: pkg={{ item }}
       update_cache=yes
       state=latest

  with_items:
  - rsyslog
  - rsyslog-doc
