---
- name: copy 50-fluentd.conf
  template: src=50-fluentd.conf
            dest=/etc/rsyslog.d/50-fluentd.conf
            owner=root
            group=root
            mode=0644
  notify: restart rsyslog
